const lines = (...items) => items

export function resolveVueioApiBaseUrl(location = window.location) {
  return location.origin
}

export function buildVueioAgentSkill({ baseUrl, keyName, userName, token }) {
  return lines(
    '---',
    'name: vue-io',
    'description: Interact with and modify Vueio projects, pages, trackers, shots, versions, comments, annotations, voice notes, files, folders, shares, notifications, and team execution data through the canonical Vueio API. Use for reading project status, organizing production work, reviewing media, posting feedback, managing assignments, and performing any operation the bound Vueio account can perform.',
    '---',
    '',
    '# Vueio',
    '',
    'Use Vueio as the source of truth for project execution and media review.',
    '',
    '## Product scope',
    '',
    '- Use Vueio for projects, pages, trackers, shots, versions, comments, media, files, shares, access, notifications, and team execution.',
    '- Work only with resources and capabilities exposed by the current Vueio installation.',
    '- Do not infer external systems or data sources that are not represented in Vueio.',
    '',
    '## Authentication and authorization',
    '',
    `- API base URL: ${baseUrl}`,
    '- Send the credential only in the `X-Vueio-Agent-Key` header.',
    `- This key acts as Vueio user: ${userName}`,
    `- Key label: ${keyName}`,
    '- The key has exactly the bound user’s current permissions. Role, app access, project grants, assignments, and visibility changes apply immediately.',
    '- A missing project, shot, comment, share, or file is inaccessible unless the user explicitly asks for an authorization diagnosis.',
    '- Use the same canonical `/api/...` routes used by the Vueio app. There is no separate agent API and no agent-specific feature-scope system.',
    '',
    '## Operating workflow',
    '',
    '1. Read current state before writing.',
    '2. Search or list projects, then drill down through tracker, shot, and version resources.',
    '3. Prefer immutable identity in this order: shot version, media asset, raw path.',
    '4. Apply the smallest mutation that satisfies the request.',
    '5. Verify writes with a focused follow-up read.',
    '6. Keep list requests bounded, normally 10–25 items, and page instead of pulling global inventories.',
    '7. Summarize large responses rather than pasting raw JSON.',
    '',
    '## Canonical project resources',
    '',
    '```text',
    'GET  /api/projects',
    'POST /api/projects',
    'GET  /api/projects/{project_id}',
    'PUT  /api/projects/{project_id}',
    'GET  /api/projects/{project_id}/contents',
    'GET  /api/projects/{project_id}/pages',
    'POST /api/projects/{project_id}/pages',
    'GET  /api/projects/{project_id}/pages/{page_ref}',
    'PUT  /api/projects/{project_id}/pages/{page_id}',
    'GET  /api/projects/{project_id}/trackers',
    'POST /api/projects/{project_id}/trackers',
    'GET  /api/projects/{project_id}/trackers/{tracker_ref}',
    'PUT  /api/projects/{project_id}/trackers/{tracker_ref}',
    'POST /api/projects/{project_id}/trackers/{tracker_ref}/shots',
    'PUT  /api/projects/{project_id}/trackers/{tracker_ref}/shots/{shot_id}',
    'GET  /api/horizons/projects/{project_id}/shots/{shot_id}/versions',
    'POST /api/horizons/projects/{project_id}/shots/{shot_id}/versions',
    '```',
    '',
    'Prefer tracker-specific shot routes. Use legacy default-tracker routes only when the canonical tracker route is not applicable.',
    '',
    '## Files, folders, and media',
    '',
    '```text',
    'GET    /api/files',
    'GET    /api/download',
    'POST   /api/download-zip',
    'POST   /api/projects/{project_id}/folders',
    'POST   /api/projects/{project_id}/import',
    'POST   /api/projects/{project_id}/link',
    'PUT    /api/projects/{project_id}/files/rename',
    'PUT    /api/projects/{project_id}/files/move',
    'DELETE /api/projects/{project_id}/files',
    '```',
    '',
    '- For resolved Horizons media, prefer shot-version or media-asset identity over a raw path.',
    '- Pass object references together with a path when a write supports both.',
    '- Respect the bound user’s File Browser access and folder permissions.',
    '',
    '## Comments and visual review',
    '',
    '```text',
    'GET  /api/comments?path={path}&project_id={project_id}',
    'POST /api/comments',
    'POST /api/comments/with-attachments',
    'POST /api/comments/{comment_id}/resolve',
    'GET  /api/comments/{comment_id}/attachments/{attachment_id}',
    'GET  /api/comments/{comment_id}/visual-context',
    'GET  /api/comments/{comment_id}/annotation.png',
    'GET  /api/comments/{comment_id}/frame.jpg',
    'GET  /api/comments/{comment_id}/annotated-frame.jpg',
    '```',
    '',
    '- Use `visual-context` when a timestamped or annotated comment needs visual understanding.',
    '- If a frame is available and an annotation exists, fetch `annotated_frame_url`; otherwise fetch `frame_url`.',
    '- Fetch attachment audio only when needed. Voice-note transcription and metadata are stored with the attachment.',
    '- Request raw annotation data only when the task specifically needs it.',
    '',
    '## Shares',
    '',
    '```text',
    'GET  /api/projects/{project_id}/shares',
    'POST /api/projects/{project_id}/share',
    'POST /api/projects/{project_id}/share-content',
    'PUT  /api/projects/{project_id}/shares/{share_id}',
    '```',
    '',
    'Create or modify shares only when the bound account has the same required project access in the app.',
    '',
    '## Users and access',
    '',
    '```text',
    'GET  /api/users',
    'POST /api/users',
    'PUT  /api/users/{user_id}',
    'GET  /api/horizons/projects/{project_id}/grants',
    'POST /api/horizons/projects/{project_id}/grants',
    '```',
    '',
    'User and grant management automatically remains admin- or owner-only because the key inherits the bound account’s authorization.',
    '',
    '## Notifications',
    '',
    '```text',
    'GET  /api/notifications/feed?limit=25&read_status=unread',
    'POST /api/notifications/read',
    'GET  /api/me/notification-preferences',
    'PUT  /api/me/notification-preferences',
    '```',
    '',
    '- Use `read_status=unread` for current activity and `read_status=read` for reviewed activity.',
    '- Page with `before_created_at` and `before_id` from the prior response.',
    '- Use focused filters such as comments, status, assignments, versions, or updates when appropriate.',
    '',
    '## Write safety',
    '',
    '- Prefer API writes. Do not edit Vueio storage or databases directly.',
    '- Preserve unknown fields and stable IDs.',
    '- Do not invent statuses or request fields; inspect the live OpenAPI schema at `/openapi.json` when a payload is unclear.',
    '- Do not retry a non-idempotent mutation blindly after an ambiguous network failure; read current state first.',
    '',
    '## Secret handling',
    '',
    '- Keep the credential local to the agent configuration.',
    '- Never reproduce it in chat, logs, screenshots, URLs, comments, project data, or tool output.',
    '- Never send it to any host other than the API base URL above.',
    '',
    '## Credential',
    '',
    '```text',
    `VUEIO_AGENT_KEY=${token}`,
    '```',
  ).join('\n')
}
